name: mitra_fintech_agent
description: A new Flutter project.
publish_to: "none"

version: 1.0.32+32

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  double_back_to_close_app: ^2.1.0
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
  dio: ^5.3.4
  #  pretty_dio_logger: ^1.3.1
  stop_watch_timer: ^3.0.2
  sms_autofill: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.2
  permission_handler: ^10.4.5
  get: ^4.6.5
  intl: ^0.17.0
  fluttertoast: ^8.2.4
  file_picker: ^6.1.1
  cached_network_image: ^3.2.3
  package_info_plus:
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  mailto: ^2.0.0
  webview_flutter: ^3.0.0
  http: ^0.13.3
  crypto: ^3.0.1
  encrypt: ^5.0.0
  flutter_dash: ^1.0.0
  shimmer: ^3.0.0
  flutter_inappwebview: ^5.7.2+3
  google_fonts: ^4.0.4
  app_version_update: ^4.0.1
  firebase_core:
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^15.1.0+1
  share_plus: ^7.1.0
  hive_flutter: ^1.1.0
  flutter_cached_pdfview: ^0.4.1
  page_transition: ^2.1.0
  image_cropper: ^4.0.1
  uni_links: ^0.5.0
  get_ip_address: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/uploadDocument/
    - assets/home/
    - assets/wallet/
    - assets/profile/
    - assets/mycases/
    - assets/uploadFiles/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
