List<String> businessProductList = [
  "Agri FMCG/ pesticides/ seeds",
  "Art gallery",
  "Automobile sales",
  "Automobiles",
  "Bakery/Cakery",
  "Bar and restaurants",
  "Battery and inverters",
  "Beds/ mattresses/ furniture",
  "Boutique/ tailoring",
  "Books/Stationary",
  "Cable Operator",
  "Cab service",
  "Canteen",
  "Chemist/ pharma distributor",
  "Circles",
  "Clothes",
  "Clothing, handloom and Textiles",
  "Cloud Kitchen",
  "Confectionary",
  "Construction material/ cylinders",
  "Construction, Interior designing and Architechture",
  "Convenience/general/kirana store",
  "Cosmetics",
  "Courier service",
  "Dance /art classes",
  "Decoration items",
  "Distribution/wholesale",
  "Distributor of FMCG",
  "Electronics and hardware",
  "Electronics, Computers, machinery and Transportation",
  "Event management",
  "Fitness",
  "Food and Beverage",
  "Food, Beverage and Tobacco Products Production",
  "Footwear",
  "Fruits and vegetables",
  "Furniture/ windows manufacturing",
  "Garment shop",
  "Glass manufacturer",
  "Gold/Diamond Jewellery",
  "Government Contractor",
  "Groceries and supermarket",
  "Hardwares and fittings",
  "Health and wellness",
  "Home appliances",
  "Home wellness",
  "Hotel/ PG/ guesthouse/ dormitory",
  "Ice-cream Parlour/ Energy drinks",
  "Imitation Jewellery",
  "Insurance",
  "Insurance Advisor",
  "Intelligence Services/Private Security Firms",
  "IT services",
  "Jewellery",
  "Kitchenware",
  "Laundry service",
  "Manpower supplier",
  "Marketing",
  "Meal kit delivery",
  "Metal Manufacturing",
  "Milk and dairy",
  "Mobile/computer accessories",
  "Mobile/computer store",
  "Newspaper",
  "NGO",
  "Pan/Tobacco retailer",
  "Paints",
  "Pet clinic/ grooming",
  "Pet supply store",
  "Pets",
  "Pipes",
  "Plumbing Products",
  "Poultry Farming/Meat Shops",
  "Publication/ printing press/ Photocopy",
  "Recharge/ money transfer service",
  "Restaurants/ Cafes/ eatery",
  "Salon and Beauty parlour",
  "School/ coaching/ classes",
  "Scrap Management",
  "Services",
  "Shelter",
  "Shoes",
  "Snacks",
  "Spa services",
  "Sports/ Club",
  "Supermarket",
  "Tiffin and catering",
  "Toiletry",
  "Toys",
  "Travel",
  "Travel and Transportation",
  "Travel agency",
  "Tobacco Products Production",
  "Tyre accessories and services",
  "Vehicle service/ Garage",
  "Video parlor",
  "Wood, Leather and Paper",
  "Others"
];

List<String> businessCategoryList = [
  "Automobiles",
  "Construction and Infrastructure",
  "Education",
  "Electronics and hardware",
  "Fashion And lifestyle",
  "Groceries and supermarket",
  "Health and wellness",
  "Home wellness",
  "Manufacturer/factory",
  "Pets",
  "Restaurants and confectionery",
  "Services",
  "Travel",
  "Travel and Transportation"
];

List<String> businessCompanyList = [
  'LLP',
  'LLC',
  'Corporation',
  'Partnership',
  'Cooperative',
  'Public',
  'Private',
  'Sole Proprietorship'
];

List<String> statesOfIndia = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  '',
];
